In [ ]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

print(df)



In [1]:
#1.Debug the given code 
# Corrected code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'],errors="coerce")  # Converts string to NaN

print(df)


   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [ ]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value)  # Error: fillna() does not modify in place

print(df)


In [2]:
#2.Corrected Code
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value,inplace=True)  # This modifies the DataFrame

print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [ ]:
#3.
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)


In [3]:
#3.Corrected Code
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5]).reshape(-1,1)  # Converts 1D array to 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [ ]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


In [4]:
#4.Corrected Code
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1,1)

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)


In [5]:
#5.Corrected Code
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  
y = le.fit_transform(y)
print(y)
model = LogisticRegression()
model.fit(X, y)


[1 0 1]


LogisticRegression()

In [ ]:
#6.
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category'])  # Error: Data should be reshaped
print(encoded)


In [9]:
#6.Corrected Code
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[['Category']])  
print(encoded)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
#7.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0]           # X and Y should have same number of samples

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
#7. Corrected Code
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0,1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train)
print(y_train)

[[7, 8], [3, 4], [1, 2]]
[1, 1, 0]


In [ ]:
#8.
from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

model = LogisticRegression()
model.fit(X_train, y_train)


In [11]:
#8.Corrected Code
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  
y_train = le.fit_transform(y_train)

model = LogisticRegression()
model.fit(X_train, y_train)


LogisticRegression()

In [ ]:
#9.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

model = LinearRegression()
model.fit(X_train, y_train)  


In [12]:
#9.Corrected code
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

X_df = pd.DataFrame(X_train)
X_filled = X_df.fillna(X_df.mean())

model = LinearRegression()
model.fit(X_filled, y_train)  

LinearRegression()

In [ ]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


In [13]:
#9.Corrected Code
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"] 
le = LabelEncoder()
y_encoded = le.fit_transform(y_train)

print(y_encoded)

model = DecisionTreeClassifier()
model.fit(X_train, y_encoded)


[1 0 1]


DecisionTreeClassifier()

In [ ]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


In [14]:
#10.Corrected Code
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

sc = StandardScaler()
x_scaled = sc.fit_transform(X_train)
model = SVC()
model.fit(x_scaled, y_train)

x_test = sc.transform([[1,150]])
print(model.predict(x_test))


[0]
